[package]
name = "workspace-atlas-desktop"
version = "0.8.3"
description = "Workspace Atlas for Desktop Start"
authors = ["Jeroen Oonincx"]
edition = "2021"

[lib]
name = "workspace_atlas_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
rfd = "0.15"
open = "5"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
